In [111]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [112]:
#Load our dataframe account for the index columns
df = pd.read_csv('case_study.csv', delimiter=',')

In [113]:
# Quickly check to see the size of our DF, both rows and columns
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34545 entries, 0 to 34544
Columns: 359 entries, Unnamed: 0 to _AIDTST3
dtypes: float64(352), int64(6), object(1)
memory usage: 94.6+ MB


Unnamed: 0  _STATE  FMONTH    IDATE  IMONTH  IDAY  IYEAR  DISPCODE  \
0           49938     9.0     5.0  5172017       5    17   2017    1200.0   
1           49939     9.0     2.0  2142017       2    14   2017    1200.0   
2           49940     9.0     1.0  1292017       1    29   2017    1200.0   
3           49941     9.0     7.0  9112017       9    11   2017    1200.0   
4           49942     9.0     5.0  7182017       7    18   2017    1200.0   
...           ...     ...     ...      ...     ...   ...    ...       ...   
34540      303774    36.0     5.0  5152017       5    15   2017    1200.0   
34541      303775    36.0     6.0  6252017       6    25   2017    1200.0   
34542      303776    36.0     7.0  7212017       7    21   2017    1200.0   
34543      303777    36.0     7.0  7202017       7    20   2017    1200.0   
34544      303778    36.0     7.0  7252017       7    25   2017    1200.0   

            SEQNO          _PSU  ...  _PA300R2  _PA30021  _PASTRNG  _PAREC1  \
0      2017000001  2.017000e+09  ...       2.0       2.0       2.0      4.0   
1      2017000002  2.017000e+09  ...       1.0       1.0       1.0      1.0   
2      2017000003  2.017000e+09  ...       3.0       2.0       1.0      3.0   
3      2017000004  2.017000e+09  ...       2.0       2.0       2.0      2.0   
4      2017000005  2.017000e+09  ...       2.0       2.0       1.0      1.0   
...           ...           ...  ...       ...       ...       ...      ...   
34540  2017012245  2.017012e+09  ...       3.0       2.0       2.0      4.0   
34541  2017012246  2.017012e+09  ...       2.0       2.0       2.0      4.0   
34542  2017012247  2.017012e+09  ...       2.0       2.0       2.0      4.0   
34543  2017012248  2.017012e+09  ...       9.0       9.0       9.0      9.0   
34544  2017012249  2.017012e+09  ...       3.0       2.0       2.0      4.0   

       _PASTAE1  _RFSEAT2  _RFSEAT3  _FLSHOT6  _PNEUMO2  _AIDTST3  
0           2.0       1.0       1.0       NaN       NaN       1.0  
1           1.0       2.0       2.0       NaN       NaN       2.0  
2           2.0       1.0       1.0       NaN       NaN       2.0  
3           2.0       1.0       1.0       NaN       NaN       1.0  
4           1.0       1.0       1.0       NaN       NaN       2.0  
...         ...       ...       ...       ...       ...       ...  
34540       2.0       1.0       1.0       NaN       NaN       1.0  
34541       2.0       1.0       1.0       NaN       NaN       1.0  
34542       2.0       1.0       1.0       NaN       NaN       1.0  
34543       9.0       9.0       9.0       9.0       9.0       9.0  
34544       2.0       1.0       1.0       NaN       NaN       1.0  

[34545 rows x 359 columns]

In [114]:
df.shape
df['_STATE'].unique()

array([ 9., 34., 36.])

## Subset your dataframe to only include the states in the tri-state area (NJ, CT, NY)

In [115]:
# your code here
#NJ = 34
#CT = 9
#NY = 36
df['_STATE'] = df['_STATE'].astype('int32')
df
#df2 = df.set_index('_STATE')#.reset_index()
df['_STATE'].unique() #array([9,34,36])

#already set to only include the states in the tristate area

array([ 9, 34, 36])

Now check to see how large our subset df.

In [116]:
# your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34545 entries, 0 to 34544
Columns: 359 entries, Unnamed: 0 to _AIDTST3
dtypes: float64(351), int32(1), int64(6), object(1)
memory usage: 94.5+ MB


**PHYSHLTH** is the column we are interested in for this analysis, so let's start to investigate the column. Since we have a data cookbook, a.k.a. data dictionary) we want to start there before looking at the code. 

In [107]:
df['PHYSHLTH'].describe()

count    34545.000000
mean        60.213403
std         37.504566
min          1.000000
25%         15.000000
50%         88.000000
75%         88.000000
max         99.000000
Name: PHYSHLTH, dtype: float64

## 1. Handle the non-normal values

As you can see from the data dictionary, there are a number of responses that are coded with values that could throw off our descriptive statistics.  Let's clean up by mapping the responses to a more appropriate value, and handling any missing values.  

In [145]:
#your code here
df['PHYSHLTH'].isna().unique() #check for nan
df['PHYSHLTH'] = df['PHYSHLTH'].astype('int64')
df['PHYSHLTH'] = df['PHYSHLTH'].replace(to_replace=88, value= 0) #0 days sick
df['PHYSHLTH-7799'] = df['PHYSHLTH'].drop([77,99,pd.nan])
#df['PHYSHLTH'].replace(to_replace=77, value=0) #dont know, if u were sick u would
#df['PHYSHLTH'].replace(to_replace=99, value=30) #chronically sick
#df['PHYSILL'] = 
df['PHYSHLTH'].unique()

AttributeError: module 'pandas' has no attribute 'nan'

## 2. Generate the descriptive statistics

Now that our target variable is cleaned up lets calculate the descriptive statistics, generate a graph that quickly shows those statistics, and generate a gprah shows the histogram of the data.

In [140]:
df['PYSHHLTH-7799'].unique()

array([ 0.,  2., 28.,  5., 30.,  4.,  3., 77., 15., 29.,  7., 10., 14.,
        6., nan,  1.,  8., 25., 99., 20., 12., 18., 27., 21., 19., 22.,
        9., 13., 17., 11., 16., 24., 26., 23.])

In [ ]:
# graphic showing those descriptive stats

In [ ]:
# graphic showing the distribution of data

## 3. Generate a graphic that compares the average number of sick days for each state. 

In [ ]:
# code to calculate the average number of sick days by state

In [ ]:
# code to graph those averages using matplotlib

## 4. Turn the number of sick days into a classification of of chronically sick people.  

Chronically sick people account for a significant proportion of the costs for health insurers. If we can identify what leads people to be chronically sick, we can address them with specific treatments.



In [16]:
# code to create new colum for chronically sick

## 5. Create a graphic that compares the percentage of people labeled as 'sick' in each state. 

In [ ]:
# code to calculate averages per state

In [ ]:
# create graphic to compare chronically sick by state

## 6. Independent Variables (categorical)

Let's take the column `SMOKDAY2` and start to prepare it so that we can see how it is possibly correlated to `PHYSHLTH`.

1. Clean up the values.
2. Calculate the descriptive statistics of the variable.
3. Generate a histogram for the variable.
4. Generate graphics that show how the responses to this variable might differ by state.
5. Generate a graphic that compares the physical health of the different groups of 'smokers'.

## 7. Independent Variables (continuous):

Now let's look at a continuous variable (ALCDAY5) and see how that might impact a person's health. 

1. Clean up the values.
2. Calculate the descriptive statistics of the variable.
3. Generate a histogram for the variable.
4. Generate graphics that show how the responses to this variable might differ by state.
5. Calculate the correlation coefficient between `PHYSHLTH` and `ALCDAY5`.
5. Generate a graphic that shows the possible relationship between `PHYSHLTH` and `ALCDAY5`.

## 8. Additional variables: Choose two additional survey items you would like to investigate do steps  6 or 7 for those variables.

In [ ]:
# your code here

## 9. Based on your initial data exploration, what are some hypotheses of what affects a person's health that you would like to further investigate?

Type out your initial hyptotheses below:

1. 

2. 

3.  

## Bonus: Create some cool graphics.  